# Generated by Django 4.1.5 on 2023-01-30 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('logo', models.FileField(upload_to='')),
                ('davlat', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=70)),
                ('qiymat', models.PositiveSmallIntegerField()),
                ('yosh', models.PositiveSmallIntegerField()),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.club')),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxmin_narx', models.PositiveSmallIntegerField()),
                ('narx', models.PositiveSmallIntegerField()),
                ('mavsum', models.CharField(max_length=10)),
                ('eski', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sotuvlar', to='app1.club')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.player')),
                ('yangi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferlar', to='app1.club')),
            ],
        ),
    ]
